GL_FUNC(glDebugMessageInsert, GLDEBUGMESSAGEINSERT);
GL_FUNC(glPushDebugGroup, GLPUSHDEBUGGROUP);
GL_FUNC(glPopDebugGroup, GLPOPDEBUGGROUP);
GL_FUNC(glObjectLabel, GLOBJECTLABEL);
GL_FUNC(glDebugMessageCallback, GLDEBUGMESSAGECALLBACK);